//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployerAddress
    {
        public byte employerAddressId { get; set; }
        public short employerId { get; set; }
        public string address { get; set; }
        public string postCode { get; set; }
        public string district { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<bool> active { get; set; }
        public string dateDeactivate { get; set; }
        public Nullable<short> createdBy { get; set; }
    
        public virtual tblEmployer tblEmployer { get; set; }
    }
}
