//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoanType()
        {
            this.tblLoans = new HashSet<tblLoan>();
        }
    
        public short loanTypeId { get; set; }
        public string loanName { get; set; }
        public bool active { get; set; }
        public byte interest { get; set; }
        public System.DateTime dateCreated { get; set; }
        public byte maxPeriod { get; set; }
        public byte minPeriod { get; set; }
        public int maxAmount { get; set; }
        public int minAmount { get; set; }
        public short createdBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoan> tblLoans { get; set; }
    }
}
