//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanSurety
    {
        public int loanId { get; set; }
        public int memberId { get; set; }
        public bool uDel { get; set; }
    
        public virtual tblLoan tblLoan { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
