//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberAddress
    {
        public int addressId { get; set; }
        public int memberId { get; set; }
        public string address { get; set; }
        public string postCode { get; set; }
        public string district { get; set; }
        public System.DateTime dateCreated { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> dateDeactivate { get; set; }
        public Nullable<short> createdBy { get; set; }
        public Nullable<bool> rent { get; set; }
    
        public virtual tblMember tblMember { get; set; }
    }
}
