//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMember()
        {
            this.tblAccountMembers = new HashSet<tblAccountMember>();
            this.tblBeneficiaries = new HashSet<tblBeneficiary>();
            this.tblLoans = new HashSet<tblLoan>();
            this.tblMemberAddresses = new HashSet<tblMemberAddress>();
            this.tblLoanSureties = new HashSet<tblLoanSurety>();
            this.tblMemberDocs = new HashSet<tblMemberDoc>();
            this.tblMemberEmployers = new HashSet<tblMemberEmployer>();
        }
    
        public int memberId { get; set; }
        public string firstName { get; set; }
        public byte gender { get; set; }
        public byte maritalStatus { get; set; }
        public string maidenName { get; set; }
        public string lastName { get; set; }
        public System.DateTime entryDate { get; set; }
        public string nic { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> memberSince { get; set; }
        public bool activePopulation { get; set; }
        public bool paidEntry { get; set; }
        public bool active { get; set; }
        public bool closed { get; set; }
        public Nullable<byte> closedBy { get; set; }
        public Nullable<System.DateTime> closedDate { get; set; }
        public byte createdBy { get; set; }
        public string reasonClosure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountMember> tblAccountMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBeneficiary> tblBeneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoan> tblLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberAddress> tblMemberAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanSurety> tblLoanSureties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberDoc> tblMemberDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberEmployer> tblMemberEmployers { get; set; }
    }
}
