//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermission()
        {
            this.tblUserPermissions = new HashSet<tblUserPermission>();
        }
    
        public short permissionId { get; set; }
        public string permissionName { get; set; }
        public short formId { get; set; }
        public bool active { get; set; }
        public bool uDelete { get; set; }
    
        public virtual tblForm tblForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserPermission> tblUserPermissions { get; set; }
    }
}
