//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserPermission
    {
        public short id { get; set; }
        public short userId { get; set; }
        public short permissionId { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public bool uDelete { get; set; }
    
        public virtual tblPermission tblPermission { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
